### ISSUE TITLE
Divide power connector requirements, L1, add sockets, and female molex on BOM

### ISSUE THREAD

**Issue by pashdown** [english1234/vstcm#11]
It is somewhat unclear as to what components are required for what style of power inputs, could this be clarified?  L1 shows a resistor, which I presume is used instead of IR, what is it? Could the sockets for the ICs and Teensy be on the BOM, along with the female molex connector that matches 09-65-2058?

**Comment by english1234** [comment]
L1 was an inductor added as an experiment but turned out not to be useful, so it was replaced with a wire link (or 0 ohm resistor). I have updated the BOM to reflect this. I have also added the Teensy, although not with a Mouser reference as it seems to be currently unavailable from them, and there are various sources for it depending on where you live in the world. As for the sockets, I have added them but again without a specific Mouser ref. I've stopped buying Molex stuff from Mouser due to cost and availability: I get most of it from Aliex now, but feel free to propose the Mouser references if you have them.

**Comment by pashdown** [comment]
Thank you for doing this.  My confusion on the sockets is that Mouser seems to have a billion different types of DIP 14 and I don't know what the spec is for the Teensy.

**Comment by english1234** [comment]
For DIP 14 the requirement is pitch of 2.54mm and row spacing of 7.62mm. I have updated the BOM with suggested Mouser references. For the Teensy I just used pin headers and sockets, which you can buy in breakable strips of 40 pins. Mouser ones seem very expensive, I get them in packs from Aliex or Amazon.
